version: '3.9'

services:
  postgres:
    container_name: events-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: testdatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    container_name: modsen-api
    image: iliyhaaa/modsentest-api:latest
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=testdatabase;Username=postgres;Password=postgres
    depends_on:
      - postgres

volumes:
  postgres-data:
