global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using ModsenTestEvent.Domain.Models;
global using ModsenTestEvent.Domain.Dtos;
global using ModsenTestEvent.Infrastructure.Data;
global using ModsenTestEvent.Infrastructure.Data.Configurations;
global using AutoMapper;
global using ModsenTestEvent.Infrastructure.Extensions;
global using ModsenTestEvent.Domain.Interfaces;
